import "../globals.css";
import Providers from "./Providers";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";

export const metadata = {
  title: "Tourism Nepal || Your trip start here with us  ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
